"""The leaf: the report schema, its serde, and the text rules packages that
cannot import each other still have to agree on.

Imports nothing else in the package — `capture`, `lint`, `report` and
`grouping` all depend on this, so anything landing here is reachable from every
one of them.
"""

from .errors import PytestGivenError, PytestGivenWarning, placeholder_mismatch
from .narration import (
    narration_of,
    narration_text,
    placeholder_token,
    placeholder_value,
    rebuilt,
    render_interpolation,
)
from .runtime import (
    ParamInfo,
    ParamSpec,
    RawParamValue,
    snapshot_param_value,
)
from .schema import (
    CONTENT_TYPES,
    PHASES,
    Activity,
    ActivityId,
    ActivityPart,
    ActivityPath,
    ActivityTermRef,
    ActivityWord,
    Attachment,
    AttachmentLabel,
    AttachmentRef,
    CellValue,
    ColumnId,
    ColumnKind,
    ContentType,
    ErrorInfo,
    Glossary,
    GlossaryTerm,
    Metadata,
    Narration,
    NarrationLiteral,
    NarrationPart,
    NarrationPlaceholder,
    NarrationTermRef,
    NarrationValue,
    NodeId,
    ParameterCase,
    ParameterColumn,
    ParameterTable,
    ParamValue,
    Phase,
    ReportData,
    Scenario,
    SourceLocation,
    Status,
    Step,
    StepAttachment,
    Story,
    StoryId,
    TermId,
    TermKind,
    TracebackFrame,
    case_suffix,
    location_suffix,
    node_base,
    param_id,
)
from .serde import report_from_dict, report_to_dict
from .steps import (
    PartIndex,
    StepPath,
    iter_narrations,
    iter_steps,
    walk_steps,
)
from .text import EMPHASIS, derived_id, id_derive

__all__ = [
    'CONTENT_TYPES',
    'EMPHASIS',
    'PHASES',
    'Activity',
    'ActivityId',
    'ActivityPart',
    'ActivityPath',
    'ActivityTermRef',
    'ActivityWord',
    'Attachment',
    'AttachmentLabel',
    'AttachmentRef',
    'CellValue',
    'ColumnId',
    'ColumnKind',
    'ContentType',
    'ErrorInfo',
    'Glossary',
    'GlossaryTerm',
    'Metadata',
    'Narration',
    'NarrationLiteral',
    'NarrationPart',
    'NarrationPlaceholder',
    'NarrationTermRef',
    'NarrationValue',
    'NodeId',
    'ParamInfo',
    'ParamSpec',
    'ParamValue',
    'ParameterCase',
    'ParameterColumn',
    'ParameterTable',
    'PartIndex',
    'Phase',
    'PytestGivenError',
    'PytestGivenWarning',
    'RawParamValue',
    'ReportData',
    'Scenario',
    'SourceLocation',
    'Status',
    'Step',
    'StepAttachment',
    'StepPath',
    'Story',
    'StoryId',
    'TermId',
    'TermKind',
    'TracebackFrame',
    'case_suffix',
    'derived_id',
    'id_derive',
    'iter_narrations',
    'iter_steps',
    'location_suffix',
    'narration_of',
    'narration_text',
    'node_base',
    'param_id',
    'placeholder_mismatch',
    'placeholder_token',
    'placeholder_value',
    'rebuilt',
    'render_interpolation',
    'report_from_dict',
    'report_to_dict',
    'snapshot_param_value',
    'walk_steps',
]
